in-memory conversation history implementation
diptanu/indexify pull request #10
Opened 2023-05-23 02:10 UTC by khshah6

2023-05-23 02:29 UTC, diptanu commented on src/server.rs
> +struct ConversationHistoryAddResponse {
@khshah6 The derive macro for serde - Serialize and Deserialize needs to be added since we are returning a Json<T> from the axum handler. This adds the Serde related methods into the struct during compilation.

2023-05-23 02:36 UTC, diptanu commented on src/server.rs
> +        let conversation_history_router = Arc::new(ConversationHistoryRouter::new(self.config.clone())?);
```
        let conv_history_router = ConversationHistoryRouter::new(self.config.clone())?;
        let conversation_history_router = Arc::new(Mutex::new(conv_history_router));
```

@khshah6  The router needs to be wrapped into Mutex as well since the handler expects that below.

I would suggest moving Mutex inside the struct so that we don't have to think about locking and such in the handler.

2023-05-23 02:41 UTC, diptanu commented on src/server.rs
> +                "/conversation_history/add",
What do you think of renaming this to `/memory/add`?

2023-05-23 14:22 UTC, diptanu commented on src/memory/lru.rs
> +fn main() {
Also another option to use a crate like - https://github.com/jeromefroe/lru-rs

2023-05-25 15:32 UTC, diptanu requested changes
The main comment is related to how we are going to handle concurrent sessions and secondly, MemoryPolicy sounds like really MemoryStoragePolicy and since it wouldn't change for a given session of an agent we could set it when the conversation starts and return a session id for subsequent add and retrieve - 
```
session = indexify.create_session(agent_id, storage_policy, extra_metadata)
indexify.add_memory(session, "hello")
indexify.add_memory(session, "world")
....
memory_events = indexify.retreive(session)
```

This will allow us to add more features to allow developers to ask Indexify to post process memory events while creating a new session.

2023-05-25 15:32 UTC, diptanu commented on src/server_config.rs
> +pub struct MemoryPolicy {
MemoryStoragePolicy?

2023-05-25 15:32 UTC, diptanu commented on src/server_config.rs
> +pub enum MemoryPolicyKind {
MemoryStoragePolicyKind ?

2023-05-25 15:32 UTC, diptanu commented on src/server.rs
> +    let result = conversation_history_lock.unwrap().add_turn(memory_policy.to_string(), payload.turn);
Moving the lock out of here int the ConversationHistory struct would be cleaner.

2023-05-27 23:43 UTC, khshah6 commented on src/server.rs
> +    let result = conversation_history_lock.unwrap().add_turn(memory_policy.to_string(), payload.turn);
Do you mean creating a function to retrieve the lock?

2023-05-28 04:03 UTC, diptanu requested changes
Looking good overall, I think the main thing remaining here - 
Use RWLock or DashMap in the MemoryRouter struct so that locks are acquired and released inside the methods of the add and retrieve methods of the router.

2023-05-28 04:03 UTC, diptanu commented on src/server_config.rs
> +    Lru,
nit: Same as above -
```
Lru{capacity: usize}
```

2023-05-28 04:03 UTC, diptanu commented on src/server.rs
> +    let result = conversation_history_lock.unwrap().add_turn(memory_policy.to_string(), payload.turn);
Responded in detail in the review.

2023-05-28 14:41 UTC, khshah6 commented on src/server.rs
> +    query: String,
yeah, for LruCache similarity scoring and other future implementations

2023-05-30 00:43 UTC, diptanu approved these changes
LGTM

2023-05-30 02:47 UTC, merged