David/pg embedding
diptanu/indexify pull request #114
Opened 2023-09-26 10:41 UTC by yenicelik

2023-09-26 21:00 UTC, diptanu requested changes

2023-09-26 21:00 UTC, diptanu commented on src/vectordbs/pg_embedding.rs
> +            Err(VectorDbError::IndexDeletionError(
If rows affected is 0, does that mean the PK exists ?

2023-09-28 21:12 UTC, yenicelik commented on src/vectordbs/pg_embedding.rs
> +            .execute(Statement::from_sql_and_values(
Yes that would work. I was thinking about the case that people may try to do SQL-injection from the frontend. I don't know enough about the whole pipeline (from API input until this stage), it may not be needed. Let me know if SQL injection is irrelevant for these, then i'll change it to from_string

2023-09-29 08:50 UTC, yenicelik commented on src/vectordbs/mod.rs
> +use sea_orm::FromQueryResult;
It is actually used here: https://github.com/diptanu/indexify/blob/ea5fbee6ab964676af946b53201b621215d66dea/src/vectordbs/mod.rs#L38 for easier querying with sea-orm. 

You are right that there's a lot of unused items, I will remove them once the PR becomes final

2023-09-29 08:59 UTC, yenicelik commented on src/vectordbs/pg_embedding.rs
> +            .execute(Statement::from_sql_and_values(
also for embedding not serializing the embeddings into the string will likely be faster, although idk enough about how sea-orm works internally here

2023-09-29 09:25 UTC, yenicelik commented on src/vectordbs/pg_embedding.rs
> +            Err(VectorDbError::IndexDeletionError(
hmm I think this can only happen if the there are no rows inserted. 
I just realized, instead of INSERT, we should probably do an UPSERT, if you want insertion to also be idempotent?

2023-09-29 09:28 UTC, yenicelik commented on src/vectordbs/pg_embedding.rs
> +            Err(VectorDbError::IndexDeletionError(
INSERT will throw an error on duplicate PKs

2023-09-29 09:47 UTC, yenicelik commented on src/vectordbs/pg_embedding.rs
> +            Err(VectorDbError::IndexDeletionError(
I just see one of the tests is called "insert idempotent", so I will change it to an UPSERT now.

2023-10-02 21:26 UTC, yenicelik commented
Includes https://github.com/diptanu/indexify/pull/117 , which was required to run it locally

2023-10-03 02:02 UTC, merged