Integrating OpenTelemetry
diptanu/indexify pull request #123
Opened 2023-10-06 20:53 UTC by yenicelik

Tracing is also exported as part of the OpenTelemetry feed

2023-10-09 15:59 UTC, diptanu requested changes
Looking great, requesting for some small changes. By the way why are we not using this package for metrics? - https://docs.rs/opentelemetry_api/0.20.0/opentelemetry_api/metrics/index.html

2023-10-09 15:59 UTC, diptanu commented on docs/docs/logs_and_metrics.md
> +You can modify the log-leve using the RUST_LOG environment variable.
log-level

2023-10-09 15:59 UTC, diptanu commented on docs/docs/logs_and_metrics.md
> +It uses the [tracing](https://docs.rs/tracing/latest/tracing/) module which asynchronously (using tokio) produces logs.
Let's remove this line, it's not very useful to operators reading the manual to learn about where and what is being logged.

2023-10-09 15:59 UTC, diptanu commented on docs/docs/logs_and_metrics.md
> +These traces are automatically displayed in stdout.
Put this under a section #### Visualizing Logs on Jaeger or something similar.

2023-10-09 15:59 UTC, diptanu commented on docs/docs/logs_and_metrics.md
> +The coordinator, executor and server individually expose metrics using [this package](https://github.com/ttys3/axum-otel-metrics).
Why not use the open telemetry metrics package? https://docs.rs/opentelemetry_api/0.20.0/opentelemetry_api/metrics/index.html

2023-10-09 15:59 UTC, diptanu commented on docs/docs/logs_and_metrics.md
> +To visualize these metrics, you can use any visualization library that can collect and parse OLTP data. In this example, we will use prometheus and grafana.
Put this in a separate sub section

2023-10-09 15:59 UTC, diptanu commented on docs/docs/logs_and_metrics.md
> +Indexify exposes logs (traces) and metrics to manage the system better.
What is the otel service name we are using? Might be worth mentioning it here.

2023-10-09 15:59 UTC, diptanu commented on src/data_repository_manager.rs
> +            .field("repository", &self.repository)
Remove the repository and vector_index_manager attributes from here. They are just manager classes and not really a 1-1 mapping between a data repository and a underlying index.

2023-10-09 15:59 UTC, diptanu commented on src/executor.rs
> +            .field("work_store", &self.work_store)
Remove the `work_store`, `attribute_index_manager` and `repository`

2023-10-09 15:59 UTC, diptanu commented on src/extractors.rs
>      module_object: PyObject,
We might be able to inject the name of the object into this while creating it. Can do in a followup pr if it's not stragihtforward.

2023-10-09 15:59 UTC, diptanu commented on src/main.rs
> +                    "indexify-service",
This should be in the switch statements below. So for server it should be indexify.api_server, for coordinator indexify.coordinator, and for the executors, indexify.executor

2023-10-09 15:59 UTC, diptanu commented on src/main.rs
> +                .with_sampler(opentelemetry::sdk::trace::Sampler::AlwaysOn),
Yeah this should probably be in config.

2023-10-09 15:59 UTC, diptanu commented on src/main.rs
> +    // TODO: We can add another global span here, before we call the individual functions
Lets do it?

2023-10-09 15:59 UTC, diptanu commented on src/main.rs
> +    info!("Spinning up");
Is this intentional?

2023-10-09 15:59 UTC, diptanu commented on src/main.rs
> +    global::shutdown_tracer_provider();
Yeah this would be at the end. Individual await blocks the servers.

2023-10-09 15:59 UTC, diptanu commented on src/vector_index.rs
> +            .field("repository", &self.repository)
Remove the repository from here.

2023-10-09 18:25 UTC, yenicelik commented on docs/docs/logs_and_metrics.md
> +Indexify exposes logs (traces) and metrics to manage the system better.
Mentioned it, maybe it's easiest if you reproduce the PR locally and modify the .md a bit more yourself

2023-10-09 18:27 UTC, yenicelik commented on src/executor.rs
> +            .field("work_store", &self.work_store)
I will also remove the Debug decorators again to keep the codebase smaller (I had added them for the sole purpose of adding these here)

2023-10-09 18:39 UTC, yenicelik commented on src/extractors.rs
>      module_object: PyObject,
hmm, seems like PyObject implements Debug. I don't see an easy way to make the debug only show the name of the object though (i dont know what will be displayed honestly). 
source code: https://docs.rs/pyo3/latest/src/pyo3/instance.rs.html#1033

we can also leave it like this for now and revisit as you mentioned

2023-10-09 18:41 UTC, yenicelik commented on docs/docs/logs_and_metrics.md
> +The coordinator, executor and server individually expose metrics using [this package](https://github.com/ttys3/axum-otel-metrics).
Is this resolved? 

this package basically uses opentelemetry metrics to compute stats about rates, errors and durations. https://github.com/ttys3/axum-otel-metrics/blob/main/src/lib.rs#L88 so we would basically be re-implementing parts of this package. it may be worth re-implementing when we want more flexibility and more metrics, but right now this is probably overkill?

2023-10-09 18:44 UTC, yenicelik commented on src/main.rs
> +                .with_sampler(opentelemetry::sdk::trace::Sampler::AlwaysOn),
turns out we should probably just control the sample-rate for now, we shouldn't make the config too complex: 
```
pub enum Sampler {
    /// Always sample the trace
    AlwaysOn,
    /// Never sample the trace
    AlwaysOff,
    /// Respects the parent span's sampling decision or delegates a delegate sampler for root spans.
    ParentBased(Box<dyn ShouldSample>),
    /// Sample a given fraction of traces. Fractions >= 1 will always sample. If the parent span is
    /// sampled, then it's child spans will automatically be sampled. Fractions < 0 are treated as
    /// zero, but spans may still be sampled if their parent is.
    /// *Note:* If this is used then all Spans in a trace will become sampled assuming that the
    /// first span is sampled as it is based on the `trace_id` not the `span_id`
    TraceIdRatioBased(f64),
    /// Jaeger remote sampler supports any remote service that implemented the jaeger remote sampler protocol.
    /// The proto definition can be found [here](https://github.com/jaegertracing/jaeger-idl/blob/main/proto/api_v2/sampling.proto)
    ///
    /// Jaeger remote sampler allows remotely controlling the sampling configuration for the SDKs.
    /// The sampling is typically configured at the collector and the SDKs actively poll for changes.
    /// The sampler uses TraceIdRatioBased or rate-limited sampler under the hood.
    /// These samplers can be configured per whole service (a.k.a default), or per span name in a
    /// given service (a.k.a per operation).
    #[cfg(feature = "jaeger_remote_sampler")]
    JaegerRemote(JaegerRemoteSampler),
}
```
TraceIdRatioBased(1.0) will correspond to AlwaysOn, so we can just accept a float in the config

2023-10-09 19:02 UTC, yenicelik commented on src/main.rs
> +    // TODO: We can add another global span here, before we call the individual functions
This may already be implemented, need to check this in the spans!

2023-10-10 05:45 UTC, diptanu approved these changes
LGTM. This is amazing, a great start towards an observable system!

2023-10-10 05:45 UTC, merged