WIP: Teach Indexify about Raft
diptanu/indexify pull request #132
Opened 2023-10-31 23:54 UTC by jackbackes

This is majorly a work in progress, as I'm learning the details of the Raft algorithm as I go :-)
Here is the status:

Done:
1. Add in-memory interface for OpenRaft
2. Add Raft management and communication APIs
3. Add Raft RPC protocol layer

TODO:

1. Integrate coordinator state into Raft state machine
2. Integrate coordinator api layer
3. Pull together and test
4. Fix merge conflicts, Clean up, document, make pretty

Future PR:

1. Sled integration

2023-10-31 23:56 UTC, jackbackes commented on Cargo.toml
> +async-trait = "0.1.74"
note to self: revert this.

2023-10-31 23:56 UTC, jackbackes commented on Cargo.toml
> +byteorder = "1.5.0"
note to self: no longer needed

2023-10-31 23:56 UTC, jackbackes commented on Cargo.toml
> +tempfile = "3.8.0"
note to self: revert this

2023-10-31 23:56 UTC, jackbackes commented on src/bin/test_raft_setup.rs
> +		// TODO: ADD THE COORDINATOR API HANDLERS HERE
Note: this is where Coordinator API handlers will go.

2023-10-31 23:58 UTC, jackbackes commented on src/coordinator.rs
> +    data: CoordinatorData,
The state machine needs serializable data so extracted the data from the repo metadata.

2023-10-31 23:58 UTC, jackbackes commented on src/raft/api.rs
> + // TODO: IMPLEMENT THIS
This is WIP

2023-10-31 23:59 UTC, jackbackes commented on src/raft/memstore.rs
> +/// TODO: update to handle the coordinator data
Todo: update to handle coordinator <-> Raft communication

2023-11-20 01:13 UTC, diptanu requested changes
Left some comments, looks like there is a bunch of duplication between various existing apis and what we are introducing to support raft. Lets use the server we already have to expose raft endpoints. In terms of the apis around requests, I think using the current types would be better than duplicating them. The Raft config should be merged with server config.

2023-11-20 01:13 UTC, diptanu commented on src/raft/raft_api.rs
> +    AxumJson(res)
write the actual type in the output?

2023-11-20 01:13 UTC, diptanu commented on src/raft/coordinator_config.rs
> +pub struct CoordinatorRaftApp {
Is this the application state ?

2023-11-20 01:13 UTC, diptanu commented on src/raft/coordinator_node.rs
> +    pub async fn run(&self) -> Result<(), anyhow::Error> {
Merge the routes here with coordinator routers with a prefix `/raft/`

2023-11-20 01:13 UTC, diptanu commented on src/raft/api.rs
> + pub(super) async fn sync_executor(
We can remove the code which does all this in the coordinator.rs, no need to maintain two different code paths.

2023-11-20 01:13 UTC, diptanu commented on src/raft/api.rs
> +pub(super) async fn embed_query(
this will go away when you rebase with master.

2023-11-20 01:13 UTC, diptanu commented on src/raft/memstore.rs
> +pub enum Request {
Yeah no need to duplicate all the enums below

2024-01-11 23:09 UTC, diptanu commented
Raft is already in!

2024-01-11 23:09 UTC, closed without merging