Add example extractors
diptanu/indexify pull request #145
Opened 2023-11-21 18:08 UTC by yenicelik

### Implemented and tested these extractors: 

- Invoice Extractor (using Donut)
- Language Extractor (provided full-text, chunks the text and predicts the language for each chunk)
- Identity Extractor (hashes the input-bytes into a vector using sha256, useful for quick duplicate-checks)

### How to reproduce:
(1) Package the extractor into a docker image `cargo run extractor package --dev -v --config-path extractors/simple_invoice_parser.yaml`
(2) Run the extractor, mounting any files required ```
docker run \
--mount type=bind,source="$(pwd)/data",target=/indexify/data \ 
-it \
--rm \
-e RUST_LOG=debug \ 
yenicelik/simple-invoice-parser extractor extract \ 
--file data/homedepot/Invoice_KulwinderSingh_05172023.pdf
```
`cargo run` can be replaced by `./target/debug/indexify` or `indexify` if the binaries were added to the `PATH`.

### For developers: 
Currently, the extractor-base image is pulled from DockerHub, due to how BuildKit works (it does not use a local registry). Unfortunately, it seems tedious to resolve this (see https://github.com/moby/buildkit/issues/2343). If you need to modify the rust code to run the extractors, please run 
- create an account for dockerhub
- modify the Makefile credentials at the top of the Makefile
- run `make build-base-extractor-push`, this will build the image, and push it to dockerhub
- modify `dockerfiles/Dockerfiles.extractor` to use your own `FROM ...`, (i.e. `FROM yenicelik/indexify-extractor-base` instead `FROM diptanu/indexify-extractor-base`).
- Then you can go to the "How to reproduce" section above

2023-11-22 05:07 UTC, diptanu requested changes
Looks great overall! Thanks David <3 
The main comment is to break down the PR into many commits, and move some code around.

2023-11-22 05:07 UTC, diptanu commented on .devcontainer/Dockerfile
> +FROM ubuntu:22.04
Can we move this dev container change into a separate PR?

2023-11-22 05:07 UTC, diptanu commented on docs/docs/develop.md
> +If docker produces a EONET error, please try to build your devcontainer prior to launching it in vscode:
Move this into the dev container pr please.

2023-11-22 05:07 UTC, diptanu commented on extractors/identity_hash_embedding.py
> +    def extract_query_embeddings(self, query: str) -> List[float]:
No longer needed.

2023-11-22 05:07 UTC, diptanu commented on extractors/identity_hash_embedding.yaml
> +name: yenicelik/identity-hash-extractor
Can we move the extractor into a separate PR ?

2023-11-22 05:07 UTC, diptanu commented on extractors/language_extractor.py
> +    def extract_query_embeddings(self, query: str) -> List[float]:
No longer needed

2023-11-22 05:07 UTC, diptanu commented on setup.py
> +    "test": ["pypdf", "span_marker", "lingua-language-detector", "parameterized"],
Do we need this anymore? If extractors are moving to their own folder, developers can put dependencies into a requirements.txt no? We can remove all these test dependencies out of here.

2023-11-22 05:07 UTC, diptanu commented on src/extractors.rs
> +            let content =
Unrelated change can we remove this from the commit ?

2023-11-22 10:24 UTC, yenicelik commented on src/extractors.rs
> +            let content =
reset it to the state of main branch now

2023-11-22 10:25 UTC, yenicelik commented on setup.py
> +    "test": ["pypdf", "span_marker", "lingua-language-detector", "parameterized"],
Hmm this was needed for the cargo tests, but redundant now, I will remove this

2023-11-22 10:57 UTC, yenicelik commented
Please make sure to merge https://github.com/diptanu/indexify/pull/146 before this

2023-11-23 17:34 UTC, yenicelik commented
Will move the extractors here https://github.com/tensorlakeai/indexify-extractors and remove them from diptanu/indexify

2023-11-23 17:34 UTC, closed without merging