Add pytorch base image for extractors via indexify.yaml
diptanu/indexify pull request #200
Opened 2024-01-03 05:29 UTC by stangirala

Add pytorch base image for extractors via indexify.yaml. Extractor config has to specify `torch`, `cuda` and `cudann` version in the yaml, see tests for example.

2024-01-03 06:28 UTC, diptanu requested changes
Looks great! Some minor style related comments and a question about how does the indexify binary make it's way into the PyTorch base image?

2024-01-03 06:28 UTC, diptanu commented on src/package.rs
> +        println!("{}", docker_file);
Remove this ?

2024-01-03 06:28 UTC, diptanu commented on src/server_config.rs
> +    pub cudann_version: String,
Probably best if you used Option<String> instead of denoting "" as unspecified.

2024-01-03 06:28 UTC, diptanu commented on src/package.rs
> +            (None, true) => { image_name = "tensorlake/indexify-extractor-base".to_string(); },
I think you could club the two statements here by something like this but I am not sure - 

```
(None, _) => {image_name = "....";},

2024-01-03 06:28 UTC, diptanu commented on src/package.rs
> +                    image_name = "pytorch/pytorch:latest".to_string();
How does the indexify binary get into this PyTorch base image? The indexify extractor base image has the indexify binary on top of a ubuntu base image.

2024-01-03 21:13 UTC, stangirala commented on src/package.rs
> +        println!("{}", docker_file);
Changed to info, just for logging.

2024-01-03 23:01 UTC, jackbackes commented on src/package.rs
> +        match (pytorch_version, gpu) {
The logic for creating the image name is fairly complex. I'm imagining a scenario where an invalid image name is being generated but it's hard to debug. At minimum I think this logic should be extracted and separately tested. You may also want to consider a more structured approach.

2024-01-03 23:02 UTC, jackbackes commented on src/package.rs
> +                image_name = "tensorlake/indexify-extractor-base".to_string();
Hardcoded values like "pytorch/pytorch:latest" and "tensorlake/indexify-extractor-base" could limit flexibility. You might consider external configuration here. Also it might make sense to generate these as lazy_static globals that can be reused throughout the application.

2024-01-03 23:04 UTC, jackbackes commented on src/package.rs
> +        info!("{}", docker_file);
this could potentially log sensitive information.

2024-01-05 23:06 UTC, stangirala commented on src/package.rs
> +                image_name = "tensorlake/indexify-extractor-base".to_string();
Left a TODO comment here, will need to follow up

2024-01-06 00:38 UTC, diptanu commented
Thanks @stangirala for this!

2024-01-06 00:38 UTC, merged