Added nightly toolchain step to setup docs
diptanu/indexify pull request #202
Opened 2024-01-03 22:28 UTC by jackbackes

Minor change to address #201 by adding a step to developer setup to install the rust nightly toolchain.

2024-01-04 20:02 UTC, diptanu requested changes
One small comment.

2024-01-04 20:02 UTC, diptanu commented on docs/docs/develop.md
> +rustup override set nightly
Do we need this? We don't depend on anything from the nightly other than formatting stuff. 

I have a make target in the Makefile which does cargo @nightly fmt or something like that which triggers the nightly toolchain only formatting.

2024-01-05 01:07 UTC, jackbackes commented on docs/docs/develop.md
> +rustup override set nightly
I ran into this issue when doing a fresh build for development setup. There were unsupported dependencies that required the nightly toolchain. IIRC it had to do with sea-orm.

I'm rebuilding it fresh so I'll see if I run into the issue again.

2024-01-05 01:26 UTC, jackbackes commented on docs/docs/develop.md
> +rustup override set nightly
I'm going to close this as "can't reproduce." I reinstalled and ran Indexify in a fresh environment and it worked fine. Maybe I had an out of date version of rustc. That will teach me to not use the dev container. ¯\_(ツ)_/¯

2024-01-05 01:26 UTC, closed without merging

2024-01-05 01:27 UTC, jackbackes commented
Can't reproduce.