Update public docs
diptanu/indexify pull request #24
Opened 2023-06-08 05:00 UTC by khshah6

- Few minor fixes
- Updating public docs with memory information, as well as some structure changes and minor fixes
- Noticed issue with search results not having associated metadata; will follow up to either add metadata to point in vector DB or run search on sql table to gather associated metadata

2023-06-08 15:17 UTC, diptanu requested changes
The main request to change here is creating a parent API page to explain that there are two APIs mainly - Rest and Python. And a conceptual overview of the api, and then link to the memory and retrieval api pages.

Unrelated to the PR - We should document clearly the optional, required fields and the default values. They don't exist for the current docs as well, I have a note to do it when I add the repository docs.

2023-06-08 15:17 UTC, diptanu commented on docs/docs/apis/embeddings.md
> +# Indexify APIs
Can we have a main APIs page - explaining how the apis are divided across memory and retrieval? From there we can have links to the individual pages.

2023-06-08 15:17 UTC, diptanu commented on docs/docs/apis/memory.md
> +    * `role` - Role (typically `Human` or `AI`).
make them lower cased? `human` and `ai`

2023-06-08 15:17 UTC, diptanu commented on docs/docs/apis/memory.md
> +* `index_args`
It's kinda weird that we ask users to specify a vector index name while creating a memory session. I think we will have the opportunity to make the UX better when we have repositories to add content and attach indexes to them in the form of "extractors" specifically for retrieval.

Just pointing it out, not requesting to change what is on the PR now.

2023-06-08 15:17 UTC, diptanu commented on docs/docs/apis/memory.md
> +* `session_id` - UUID corresponding to memory session.
Can we relax this by allowing users to specify non-UUID based identifiers as well? So basically string based unique identifiers. in the event they are not passed we can create it for them as you already have.

2023-06-09 15:20 UTC, diptanu requested changes

2023-06-09 15:20 UTC, diptanu commented on src/server.rs
> +        successful: true
Do we need this? Under what conditions would this be successful: false, and not return IndexifyAPIError?

2023-06-09 15:20 UTC, diptanu commented on src/persistence.rs
> +        let tx = self
I believe this will change based on the other PR.

2023-06-09 15:20 UTC, diptanu commented on docs/docs/develop.md
> +python3.11 -m venv ve
Do we have a hard dependency on 3.11 can we use `python3` instead? I think that would alias to python3.11 or python 3.9 on most systems.

2023-06-09 20:13 UTC, khshah6 commented on docs/docs/develop.md
> +python3.11 -m venv ve
thats fine, we'll just have to modify this then

`export PYTHONPATH=${PYTHONPATH}:${PWD}/ve/lib/python3.11/site-packages`

2023-06-10 00:01 UTC, khshah6 commented on src/persistence.rs
> +        let tx = self
We decided to leave it as is for now

2023-06-10 00:02 UTC, khshah6 commented on docs/docs/apis/embeddings.md
> +# Indexify APIs
sure, added

2023-06-10 14:50 UTC, diptanu approved these changes
LGTM!

2023-06-10 14:51 UTC, merged