Bug Fix + Refactor python SDK to be friendly with setuptools
diptanu/indexify pull request #46
Opened 2023-06-28 02:42 UTC by Vijay2win

2023-06-28 04:41 UTC, diptanu requested changes
Thanks, looks great! Small nits in code, and let’s bring back the pyproject related files, which is currently being used to build and push to pypi.

2023-06-28 04:41 UTC, diptanu commented on sdk-py/poetry.lock
This needs to come back.

2023-06-28 04:41 UTC, diptanu commented on sdk-py/pyproject.toml
This needs to come back. We are using poetry to package, distribute and push the package to pypi - https://pypi.org/project/indexify/

2023-06-28 04:41 UTC, diptanu commented on sdk-py/setup.py
This is not required as pyproject is recommended over setuptools.

2023-06-28 04:41 UTC, diptanu commented on sdk-py/requirements.txt
Dependencies should be in pyproject

2023-06-28 04:41 UTC, diptanu commented on sdk-py/indexify/memory.py
> +    DEFAULT_INDEXIFY_URL = "http://localhost:8900"
Please move this in a const file or something as bunch of classes would refer to it.

2023-06-28 04:41 UTC, diptanu commented on sdk-py/indexify/utils.py
> +    if "errors" in payload.keys() and len(payload["errors"]) > 0:
We no longer have errors in payload, so not required.

2023-06-28 04:41 UTC, diptanu commented on sdk-py/indexify/index.py
> +    def sync(self, name: str, extractor_type):
Please remove this or fix the signature of the sync method - its name and a list of extractors.

2023-06-28 04:41 UTC, diptanu commented on sdk-py/indexify/data_containers.py
> +class SearchChunk:
Does this work? Assuming this is a data class, so probably needs a @dataclass decorator?

2023-06-28 04:41 UTC, diptanu commented on sdk-py/indexify/data_containers.py
> +class Message:
Make this a data class?

2023-06-28 04:41 UTC, diptanu commented on sdk-py/examples/question_answer_demo.py
This is a great! I think it would work really well if this was a notebook, then we could have embedded it right in the docs of the website :)

2023-06-28 04:44 UTC, diptanu requested changes

2023-06-28 04:44 UTC, diptanu commented on sdk-py/Makefile
Can we also bring this back? This has some handy scripts to lint and build the package.

2023-06-28 05:20 UTC, diptanu commented on sdk-py/examples/simple_example.py
There is a notebook in the docs - https://github.com/diptanu/indexify/blob/main/docs/docs/python_sdk.ipynb If you update that, it will automatically get compiled and published on the website.

2023-06-30 03:48 UTC, jjmachan commented on sdk-py/poetry.lock
the poetry.lock file does not have to be added for libraries and SDKs right? pip will be able to take it from pyproject or setup.py and whatever is installed on the user's system. If we lock it that limits things at the user end I believe?

2023-06-30 05:40 UTC, diptanu commented on sdk-py/poetry.lock
Good point @jjmachan but the other issue is version mismatch of what we test with vs what the user has could lead to inconsistent behavior/bugs.

2023-06-30 05:45 UTC, merged