Refactor SDK / dependency improvements
diptanu/indexify pull request #65
Opened 2023-07-05 04:20 UTC by Vijay2win

move things around so there is one SDK director and minor documentation. Moved langchain to extra dependency

2023-07-05 06:19 UTC, diptanu requested changes
* Please remove the .idea files 
* Move langchain integration under a langchain top level folder such that the imports read something like - `from indexify.langchain.memory import Indexify` - This is similar to how other langchain memory implementations currently look. Also in it's current form it's hard to tell the difference between `from indexify import Memory` and `from indexify import IndexifyMemory`

2023-07-05 06:19 UTC, diptanu commented on sdk-py/examples/agent_memory.py
> +from indexify import IndexifyMemory, DEFAULT_INDEXIFY_URL
Please put IndexifyMemory under a langchain module, so that reads -

`from indexify.langchain.memory import Indexify`
This is how all langchain memory implementations look.

2023-07-05 06:19 UTC, diptanu commented on sdk-py/indexify/__init__.py
> +from .langchain_wrappers import IndexifyMemory
Move this under a langchain module `langchain/memory`, we will have to add a retriever module as well in the future for langchain.

2023-07-16 23:26 UTC, Vijay2win commented
Lets merge this. I will address the comments in the #69

2024-01-11 23:10 UTC, diptanu commented
Closing this as we have re-worked the SDK structure

2024-01-11 23:10 UTC, closed without merging