Updates to python sdk for new server api
diptanu/indexify pull request #95
Opened 2023-08-16 22:56 UTC by shabani1

There are a number of things still broken that we need to implement on the server side, and I added new FIXME comments here for each of them.

2023-08-16 23:00 UTC, shabani1 commented
This is a good stopping point for this PR since I can't make more changes without changing the server side. Want to get these in first and then do the server fixes in tandem.

2023-08-17 00:04 UTC, shabani1 commented
Pushed an update, I realized what the query attribute endpoint needs so updated that call so it's now working.

2023-08-17 01:03 UTC, diptanu requested changes

2023-08-17 01:03 UTC, diptanu commented on docs/docs/getting_started.md
> +    repo.bind_extractor("EntityExtractor", index_name="entityindex")
Add filters attribute here?

2023-08-17 01:03 UTC, diptanu commented on sdk-py/README.md
> +## Development
This is the README that a developer will see on pypi. So we want a different set of instructions here like -

```
pip install indexify
```

And then some examples of how to use the client.

2023-08-17 01:03 UTC, diptanu commented on sdk-py/examples/benchmark.py
> +        self.repository = ARepository(, url
Is this a typo?

2023-08-17 01:03 UTC, diptanu commented on src/server.rs
> +    // TODO: shouldn't index_name be required here?
Extractor Bindings create indexes, not the other way round. The payload contains the index_name that the binding will populate.

2023-08-17 01:03 UTC, diptanu commented on src/vector_index.rs
> +            // FIXME: "{}/{}" should be "{}.{}" or some other separator that's not url encoded
I agree, but does it cause any issues?

2023-08-17 01:20 UTC, shabani1 commented on docs/docs/develop.md
> -make migrate-dev
Oh yea, good point. I had removed it because the command was above, but we need it here too.

2023-08-17 01:26 UTC, shabani1 commented on docs/docs/getting_started.md
> +        {"text": "Indexify is amazing!"},
For the getting started, I think it's much more clear this way. This was some of the feedback that I provided the first time I looked at this, which is "as a developer, it's not clear to me where those metadata topics came from, and most of my docs won't have that. They look like things that would get created by an extractor."

I agree that the filter feature for the bindings is a great one. Would it be okay if we kept this and then demonstrated that example as part of a different tutorial? Like a separate extractors tutorial or something? I just want this part to be crystal clear to someone seeing indexify for the first time.

2023-08-17 01:27 UTC, shabani1 commented on docs/docs/getting_started.md
> +    repo.bind_extractor("EntityExtractor", index_name="entityindex")
It's there as a default argument right now. Python method has the value here as the default.

2023-08-17 01:28 UTC, shabani1 commented on sdk-py/README.md
> +## Development
Oh crap, you're right! I was writing notes for myself for which steps to repeat each time, and I shouldn't have put them here. Will update.

2023-08-17 01:29 UTC, shabani1 commented on sdk-py/examples/benchmark.py
> +        self.repository = ARepository(, url
Must've screwed this up in the refactor 🤔

2023-08-17 01:34 UTC, shabani1 commented on src/server.rs
> +    // TODO: shouldn't index_name be required here?
Right, that's what I'm saying. But currently in the payload, the index_name is [optional](https://github.com/diptanu/indexify/blob/e34cf94e018d8bbe19c8bdc23d922e65f3500a34/src/api.rs#L79), shouldn't it be required?

2023-08-17 01:38 UTC, shabani1 commented on src/vector_index.rs
> +            // FIXME: "{}/{}" should be "{}.{}" or some other separator that's not url encoded
It creates ambiguity for the qdrant API, since collection name has a slash in it. For example, I can't visit `http://localhost:6333/collections/default/embeddingindex` to view my embedding index stats, I have to visit `http://localhost:6333/collections/default%2Fembeddingindex` instead. If it's not difficult to change might be worth doing it now.

2023-08-17 01:52 UTC, shabani1 commented
Made requested changes.

2023-08-17 02:13 UTC, diptanu commented on docs/docs/getting_started.md
> +        {"text": "Indexify is amazing!"},
Got it. Can you please add some examples with filters?

2023-08-17 02:35 UTC, shabani1 commented on docs/docs/getting_started.md
> +        {"text": "Indexify is amazing!"},
As discussed, will add new examples with filters in a future PR. For now, keeping the metadata in CURL examples.

2023-08-17 02:39 UTC, merged